// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI3zI4YY87LvRmaOWvsctI8Oxr2ZRuJWQ',
    appId: '1:266840291575:web:b11a8ef4567d98e76cfbf2',
    messagingSenderId: '266840291575',
    projectId: 'app-pelaporan-61fea',
    authDomain: 'app-pelaporan-61fea.firebaseapp.com',
    storageBucket: 'app-pelaporan-61fea.firebasestorage.app',
    measurementId: 'G-6027TCD1VL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5s8ne5_lxHpcCwR-U2Ih3eGzVmITPG2c',
    appId: '1:266840291575:android:2037ac18e2af61e26cfbf2',
    messagingSenderId: '266840291575',
    projectId: 'app-pelaporan-61fea',
    storageBucket: 'app-pelaporan-61fea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM1P3MiQhjgA9q79Jiy1Gb31-O4lgbBXw',
    appId: '1:266840291575:ios:a60c67e5ecea16b76cfbf2',
    messagingSenderId: '266840291575',
    projectId: 'app-pelaporan-61fea',
    storageBucket: 'app-pelaporan-61fea.firebasestorage.app',
    iosBundleId: 'com.example.appPengaduan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM1P3MiQhjgA9q79Jiy1Gb31-O4lgbBXw',
    appId: '1:266840291575:ios:a60c67e5ecea16b76cfbf2',
    messagingSenderId: '266840291575',
    projectId: 'app-pelaporan-61fea',
    storageBucket: 'app-pelaporan-61fea.firebasestorage.app',
    iosBundleId: 'com.example.appPengaduan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI3zI4YY87LvRmaOWvsctI8Oxr2ZRuJWQ',
    appId: '1:266840291575:web:9c4c8cad83b9ee6e6cfbf2',
    messagingSenderId: '266840291575',
    projectId: 'app-pelaporan-61fea',
    authDomain: 'app-pelaporan-61fea.firebaseapp.com',
    storageBucket: 'app-pelaporan-61fea.firebasestorage.app',
    measurementId: 'G-GRQFC7LVGR',
  );
}
